"ui.background" = { bg = "black" }
"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "red"}
"ui.text.info" = { fg = "white" }

"ui.selection" = { bg = "darkgrey" }
"ui.cursor" = { fg = "lightgrey", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "yellow", modifiers = ["reversed"] }
"ui.cursor.match" = { bg = "darkgrey", modifiers = ["underlined", "bold"] }

"ui.gutter" = { bg = "lightblack" }
"ui.gutter.selected" = { bg = "darkgrey" }
"ui.linenr" = { fg = "grey", bg = "lightblack" }
"ui.linenr.selected" = { fg = "lightgrey", bg = "darkgrey", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "darkgrey" }

"ui.statusline" = { fg = "lightgrey", bg = "darkgrey" }
"ui.statusline.inactive" = { fg = "grey", bg = "lightblack" }
"ui.statusline.normal" = { modifiers=["bold"] }
"ui.statusline.insert" = { modifiers=["reversed", "bold"] }
"ui.statusline.select" = { fg="green_faded", modifiers=["reversed", "bold"] }
"ui.bufferline" = { fg = "lightgrey", bg = "lightblack" }
"ui.bufferline.active" = { fg = "lightgrey", bg = "darkgrey", modifiers=["bold"] }

"ui.popup" = { fg = "grey", bg = "#222230" }
"ui.help" = { fg = "aqua_faded", bg = "#001020" }
"ui.menu" = { fg = "#d0d0a0", bg = "#222230" }
"ui.menu.selected" = { fg = "aqua", modifiers=["bold"] }

"ui.picker" = {bg = "darkRed"}

"ui.virtual.ruler" = { bg= "lightblack" }
"ui.virtual.inlay-hint" = { fg = "grey" }

"ui.window" = { bg = "lightblack" }
"comment" = { fg = "orange", modifiers = ["italic"] }
"operator" = { fg = "red", modifiers = ["bold"] }
"variable" = "yellow"
"constant" = "pink"
"attribute" = "orange"
"type" = { fg="aqua", modifiers=["bold"] }
"type.builtin" = "aqua_faded"
"punctuation.delimiter" = "lightgrey"
"punctuation.bracket" = "lightgrey"
"string"  = "pink"
"variable.other.member" = "yellow"
"constant.character.escape" = { fg="red", modifiers=["reversed"] }
"function" = "green"
"constructor" = "green"
"special" = "green"
"keyword" = { fg = "lightgrey", modifiers = ["bold"] }
"keyword.storage.modifier" = "aqua_faded"
"label" = "pink"
"namespace" = "pink"

"markup.heading" = { fg="green", modifiers = ["bold"]}
"markup.raw.inline" = { fg="yellow", modifiers = ["bold"]}
"markup.bold" = { fg = "green", modifiers = ["bold"] }
"markup.italic" = { fg = "orange", modifiers = ["italic"] }
"markup.link.url" = { fg = "purple", modifiers = ["underlined"] }
"markup.link.text" = "red"
"markup.quote" = "yellow_faded"

"diff.plus" = "yellow"
"diff.delta" = "purple"
"diff.minus" = "red"

"diagnostic.hint" = { underline = { style="line", color="grey" } }
"diagnostic.info" = { underline = { style="line", color="aqua" } }
"diagnostic.warning" = { underline = { style="curl", color="yellow" } }
"diagnostic.error" = { underline = { style="curl", color="red" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"hint" = {fg="gray", modifiers = ["bold","italic"]}
"info" = {fg="aqua", modifiers = ["bold","italic"]}
"error" = {fg="darkRed", modifiers = ["bold","italic"]}
"warning" = {fg="orange", modifiers = ["bold","italic"]}

[palette]
black = "#1c1c1c"
lightblack = "#222222"
darkgrey = "#333333"
grey = "#777777"
lightgrey = "#a0a0a0"
white = "#e4e4e4"
orange = "#dfaf5f"
darkOrange = "#443300"
darkRed = "#c02060"
purple = "#cfB7ff"
aqua = "#83c6dd"
aqua_faded = "#8fd7ff"
yellow = "#d8d88d"
yellow_faded = "#bbbb99"
green = "#86d265"
green_faded = "#9fb740" 
red = "#ff0080"
pink = "#eeaacc"
