theme = "eddy"

[editor]
cursorline = true
rulers = [80]
color-modes = true
bufferline = "multiple"
true-color = true

[editor.statusline]
left = ["mode", "separator", "file-type", "diagnostics"]
center = ["file-name"]
right = ["selections","separator","position-percentage", "position"]
separator = "▏"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
max-depth = 0

[editor.lsp]
display-inlay-hints = true
