theme = "eddy"

[editor]
cursorline = true
rulers = [80]
color-modes = true
bufferline = "multiple"
true-color = true
auto-pairs = false
completion-trigger-len = 0
idle-timeout = 0

[editor.statusline]
left = ["mode", "separator", "file-type", "diagnostics"]
center = ["file-name"]
right = ["selections","separator","position-percentage", "position"]
separator = "▏"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.file-picker]
max-depth = 0

[editor.lsp]
display-inlay-hints = true
goto-reference-include-declaration = false

[keys.normal]
C-h = ":toggle lsp.display-inlay-hints"

[keys.insert]
C-h = ":toggle lsp.display-inlay-hints"
