theme = "eddy"

[editor]
cursorline = true
rulers = [80]
color-modes = true
bufferline = "multiple"

[editor.statusline]
left = ["mode", "separator", "file-type", "diagnostics"]
center = ["file-name"]
right = ["selections","separator","position-percentage", "position"]
separator = "▏"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"